apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
{{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ randAlphaNum 24 | b64enc | quote }}
  mariadb-password: {{ randAlphaNum 24 | b64enc | quote }}
  mariadb-host: {{ include "wordpress.mariadb.fullname" . | b64enc | quote }}
{{ end }}
