{{- $secretName := include "wordpress.fullname" . -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{ if ! $existing }}
{{- $rootPlain := randAlphaNum 24 | b64enc | quote }}
{{- $passPlain :=  randAlphaNum 24 | b64enc | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
{{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ $rootPlain }} 
  mariadb-password: {{ $passPlain }}
  mariadb-host: {{ include "wordpress.mariadb.fullname" . | b64enc | quote }}
{{ end }}
