apiVersion: v2
name: wordpress
description: A comprehensive Helm chart for deploying WordPress on Kubernetes, including MariaDB as the database backend.
home: https://github.com/Linuxgurus/wordpress-helm
icon: https://s.w.org/style/images/about/WordPress-logotype-wmark.png
sources:
  - https://github.com/Linuxgurus/wordpress-helm
  - https://github.com/wordpress/wordpress
maintainers:
  - name: James Blackwell
    email: jblack@linugxuru.net
keywords:
  - wordpress
  - cms
  - blog
  - mariadb
  - database
  - php

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.29

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "6.9.0"
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "Initial release of the WordPress Helm chart"
    - kind: changed
      description: "Updated documentation for better clarity and Artifact Hub support"
  artifacthub.io/category: cms
  artifacthub.io/language: php
  artifacthub.io/license: GPL-2.0
