apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.mariadb.fullname" . }}
  labels:
    {{- include "wordpress.mariadb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.storage.size | quote }}
