apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.wordpress.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size | quote }}
  {{- if .Values.wordpress.persistence.storageClass }}
  storageClassName: {{ .Values.wordpress.persistence.storageClass | quote }}
  {{- end }}
